# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OBgMz_lc_clQ1vPpyJmt8T4i8HbGDpN6
"""

import numpy as np

a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

print(a)

print(a.shape)

mean_a = np.mean(a, axis = 0)

print(mean_a)

a_centered = a-mean_a

print(a_centered)

a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])

print(a_centered_sp)

a_centered_sp / 4

np.cov(a.transpose())[0,1]